// ignore: unused_import
import 'package:flutter/material.dart';

List<String> getLyrics() {
  return [
    'I woke up in a dream today',
    'To the cold of the static and',
    'Put my cold feet on the floor',
    'Forgot all about yesterday',
    'Remembering Im pretending',
    ' to be where Im not anymore',
    'A little taste of hypocrisy',
    'And Im left in the wake',
    'of the mistake, slow to react',
    'Even though youre so close to me',
    'Youre still so distant and ',
    'I cant bring you back',
    'Its true',
    'The way I feel',
    'Was promised by your face',
    'The sound of your voice',
    'Painted on my memories',
    'Even if youre not with me',
    'Im with you',
    'You now I see',
    'Keeping everything inside (with you)',
    'You now I see',
    'Even when I close my eyes',
    'I hit you and you hit me back',
    'We fall to the floor,',
    'the rest of the day stands still',
    'Fine line between this and that',
    'When things go wrong',
    'I pretend that the past isnt real',
    'Now Im trapped in this memory',
    'And Im left in the wake of',
    'the mistake, slow to react',
    'So even though youre close to me',
    'Youre still so distant and',
    'I cant bring you back',
    'Its true',
    'The way I feel',
    'Was promised by your face',
    'The sound of your voice',
    'Painted on my memories',
    'Even if youre not with me',
    'Im with you',
    'You now I see',
    'Keeping everything inside (with you)',
    'You now I see',
    'Even when I close my eyes',
    'Im with you',
    'You now I see',
    'Keeping everything inside (with you)',
    'You now I see',
    'Even when I close my eyes',
    'No, no matter how far weve come',
    'I cant wait to see tomorrow',
    'No matter how far weve come I',
    'I cant wait to see tomorrow',
    'With you',
    'You now I see',
    'Keeping everything inside (with you)',
    'You now I see',
    'Even when I close my eyes',
    'With you',
    'You now I see',
    'Keeping everything inside (with you)',
    'You now I see',
    'Even when I close my eyes',
  ];
}
